name: Build TNOB Calendar

on:
  schedule:
    - cron: "0 2 1 * *"  # каждый 1-й день месяца в 02:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run generate script
        run: node generate.js
